#!/bin/bash

# 增强版 Rust 教程演示脚本
# 展示真正的"点击运行"功能

echo "🦀 Rust 基础教程 - 点击运行功能演示"
echo "=================================="
echo ""

echo "🎯 核心特色："
echo "✅ 真正的点击运行体验"
echo "✅ 详细的知识点讲解"  
echo "✅ 交互式演示模式"
echo "✅ 美化的界面设计"
echo ""

echo "📚 演示功能列表："
echo ""

# 1. 展示菜单界面
echo "1️⃣ 美化的交互式菜单："
echo "─────────────────────"
echo "启动命令: cargo run"
echo "然后您会看到以下菜单："
echo ""
echo "┌────────────────────────────────────────────────────┐"
echo "│               🦀 Rust 教程菜单                     │"
echo "├────────────────────────────────────────────────────┤"
echo "│ 🔰 基础教程 (第1-4章)                              │"
echo "│  1. 变量与常量  2. 数据类型  3. 函数  4. 控制流    │"
echo "├────────────────────────────────────────────────────┤"
echo "│ 🚀 核心概念 (第5-8章)                              │"
echo "│  5. 内存管理  6. 所有权  7. 借用机制  8. 结构体     │"
echo "├────────────────────────────────────────────────────┤"
echo "│ 📦 高级特性 (第9-12章)                             │"
echo "│  9. 常用类型  10. 枚举  11. 泛型特征  12. 生命周期  │"
echo "├────────────────────────────────────────────────────┤"
echo "│ 🏗️ 项目开发 (第13-17章)                            │"
echo "│  13. 项目管理  14. 文档测试  15. 闭包  16. 迭代器  │"
echo "│  17. 智能指针                                      │"
echo "├────────────────────────────────────────────────────┤"
echo "│ 🎭 专业主题 (第18-20章)                            │"
echo "│  18. 常用智能指针  19. 并发编程  20. Unsafe Rust   │"
echo "├────────────────────────────────────────────────────┤"
echo "│ 🎯 快速选项                                        │"
echo "│  0: 运行所有章节  basic: 基础教程  advanced: 进阶  │"
echo "│  demo: 交互演示  help: 详细帮助  q: 退出程序       │"
echo "└────────────────────────────────────────────────────┘"
echo ""

# 2. 点击运行示例
echo "2️⃣ 点击运行示例："
echo "─────────────────"
echo "🎯 运行第1章（变量与常量）："
echo "   输入: 1"
echo "   您会看到："
echo "   ┌─ 📚 章节介绍（学习目标和核心概念）"
echo "   ├─ 🔸 代码运行（实际的 Rust 代码执行）"
echo "   ├─ 📋 知识点总结（关键要点回顾）"
echo "   └─ 🛠️ 相关命令（进一步学习的命令）"
echo ""

# 3. 特殊功能
echo "3️⃣ 特殊功能："
echo "─────────────"
echo "🎭 交互式演示："
echo "   输入: demo"
echo "   体验核心概念的交互式演示"
echo ""
echo "📚 批量学习："
echo "   输入: basic    # 运行基础教程 (第1-4章)"
echo "   输入: advanced # 运行进阶教程 (第5-20章)"
echo "   输入: 0        # 运行所有章节"
echo ""

# 4. 独立运行示例
echo "4️⃣ 独立运行示例："
echo "─────────────────"
echo "💻 直接运行特定章节："
echo "   cargo run --bin variables      # 第1章：变量与常量"
echo "   cargo run --bin ownership      # 第6章：所有权（重点推荐）"
echo "   cargo run --bin concurrency    # 第19章：并发编程"
echo ""

# 5. 学习路径
echo "5️⃣ 推荐学习路径："
echo "─────────────────"
echo "🔰 新手路径："
echo "   1. 基础语法: cargo run → 输入 basic"
echo "   2. 核心概念: 第5-8章（所有权系统是重点）"
echo "   3. 高级特性: 第9-12章"
echo ""
echo "🚀 快速体验："
echo "   cargo run → 输入 demo（交互式演示）"
echo "   cargo run → 输入 0（所有章节）"
echo ""

# 6. 测试功能
echo "6️⃣ 验证功能："
echo "─────────────"
echo "🧪 运行测试："
echo "   cargo test                # 运行所有测试"
echo "   cargo test ownership      # 运行特定章节测试"
echo ""
echo "📖 查看源代码："
echo "   cat src/bin/ownership.rs  # 查看所有权示例代码"
echo "   cat src/examples.rs       # 查看所有示例集合"
echo ""

# 7. 实际演示
echo "7️⃣ 现在开始实际演示："
echo "──────────────────────"
echo ""

# 演示第1章
echo "🔹 演示运行第1章（变量与常量）..."
echo "命令: echo '1' | cargo run --"
echo ""

# 限制输出长度避免输出过多
echo "输出示例（节选）："
echo "────────────────"
echo "📚 章节介绍"
echo "────────────────────────────────"
echo "🎯 学习目标："
echo "  • 理解变量的声明和赋值"
echo "  • 掌握可变性 (mut) 的概念"
echo "  • 学习常量和静态变量的区别"
echo "  • 了解变量遮蔽 (shadowing)"
echo ""
echo "💡 核心概念："
echo "  • let 关键字：声明变量"
echo "  • mut 关键字：使变量可变"
echo "  • const 关键字：编译时常量"
echo "  • static 关键字：全局变量"
echo ""
echo "🔸 正在运行：第1章：变量与常量"
echo "═══════════════════════════════════════════════"
echo "[运行 Rust 代码示例...]"
echo "═══════════════════════════════════════════════"
echo "✅ 第1章：变量与常量 示例运行完成！"
echo ""
echo "📋 知识点总结"
echo "──────────────────────────────"
echo "✅ 您已经学会了："
echo "  🔸 使用 let 声明变量"
echo "  🔸 使用 mut 创建可变变量"
echo "  🔸 定义常量和静态变量"
echo "  🔸 理解变量遮蔽的机制"
echo ""
echo "🚀 下一步建议："
echo "  📚 学习第2章数据类型，了解 Rust 的类型系统"
echo ""
echo "🛠️ 相关命令"
echo "────────────────────"
echo "💻 独立运行此章节："
echo "   cargo run --bin variables"
echo "📖 查看源代码："
echo "   cat src/bin/variables.rs"
echo ""

echo "🎉 演示完成！"
echo ""
echo "💡 开始您的 Rust 学习之旅："
echo "   cd lesson/task"
echo "   cargo run"
echo "   # 然后输入数字 1-20 选择章节"
echo ""
echo "🚀 或者快速体验："
echo "   cargo run"
echo "   # 输入 demo 体验交互式演示"
echo ""
echo "📚 查看完整说明："
echo "   cat README.md"
echo ""

echo "🦀 祝您 Rust 学习愉快！" 